In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-4.1446e-27,  6.9364e-43, -4.1446e-27],
        [ 6.9364e-43, -4.1449e-27,  6.9364e-43],
        [-4.1449e-27,  6.9364e-43, -4.1451e-27],
        [ 6.9364e-43, -4.1451e-27,  6.9364e-43],
        [-4.1453e-27,  6.9364e-43, -4.1453e-27]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1965, 0.3184, 0.1574],
        [0.6491, 0.1940, 0.1484],
        [0.2325, 0.6262, 0.8477],
        [0.8616, 0.1134, 0.5641],
        [0.9719, 0.2316, 0.2538]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
x = x.new_ones(5, 3, dtype=torch.double) 
print(x)   # 只继承原张量的设备和一些默认设置，但是大小和数据内容是你指定的
# 一般用来新建张量，只是懒得手动写 device、layout 这些信息

x = torch.randn_like(x, dtype=torch.float)    
print(x)   #自动继承原张量的大小、dtype、device。    

# new_* 方法（如 new_ones），你手动指定。	*_like 方法（如 randn_like）从原张量继承

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4925, -0.3053,  0.8941],
        [ 1.9578,  0.4961,  0.0958],
        [ 2.2385, -3.1177, -1.7837],
        [ 0.0400, -0.5056,  0.2458],
        [ 0.7394,  0.3600, -0.1258]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1099,  0.2031,  1.4949],
        [ 2.4997,  0.6404,  0.5476],
        [ 2.6593, -2.4655, -0.8476],
        [ 0.7175,  0.1952,  0.5110],
        [ 1.5351,  0.5708, -0.1231]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[-0.1099,  0.2031,  1.4949],
        [ 2.4997,  0.6404,  0.5476],
        [ 2.6593, -2.4655, -0.8476],
        [ 0.7175,  0.1952,  0.5110],
        [ 1.5351,  0.5708, -0.1231]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1099,  0.2031,  1.4949],
        [ 2.4997,  0.6404,  0.5476],
        [ 2.6593, -2.4655, -0.8476],
        [ 0.7175,  0.1952,  0.5110],
        [ 1.5351,  0.5708, -0.1231]])


Addition: in-place



In [ ]:
# adds x to y   in-place操作
y.add_(x) 
print(y) #直接修改原始张量的值，不会返回新张量。

tensor([[-0.1099,  0.2031,  1.4949],
        [ 2.4997,  0.6404,  0.5476],
        [ 2.6593, -2.4655, -0.8476],
        [ 0.7175,  0.1952,  0.5110],
        [ 1.5351,  0.5708, -0.1231]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-0.3053,  0.4961, -3.1177, -0.5056,  0.3600])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16) #重塑（reshape） -1 表示“自动推断”。
z = x.view(-1, 8) 
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item()) #.item() 是 从单元素张量中提取出其纯 Python 数值

tensor([-0.6945])
-0.6945067048072815



**稍后阅读：**

超过 100 种张量操作，包括转置、索引、切片、数学运算、线性代数、随机数生成等等，已经在
[这里](https://pytorch.org/docs/torch) 描述。

## NumPy 桥接

将一个 Torch 张量（Tensor）转换为 NumPy 数组，或者反过来转换，操作非常简单。

如果 Torch 张量在 **CPU** 上，Torch 张量和 NumPy 数组会**共享底层内存**，因此**修改其中一个，另一个也会跟着变化**。

### 将 Torch 张量转换为 NumPy 数组




In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy() #Tensor 在 CPU 上时，才能 .numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b) #共享内存

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) #把 NumPy 数组 a 转成 PyTorch 张量 b。
np.add(a, 1, out=a) #这个张量 b 与 NumPy 数组 a 共享内存
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# 仅当 CUDA 可用时，运行这段代码
# 我们将使用 `torch.device` 对象，把张量在 CPU 和 GPU 之间移动

if torch.cuda.is_available():
    device = torch.device("cuda")          # 创建一个 CUDA 设备对象（GPU）
    y = torch.ones_like(x, device=device)  # 直接在 GPU 上创建一个和 x 同形状的全1张量
    x = x.to(device)                       # 把原本的 x 复制到 GPU 上
    z = x + y                              # 在 GPU 上进行加法运算
    print(z)
    print(z.to("cpu", torch.double))       # 把 z 移回 CPU，同时改成 double 类型


tensor([0.3055], device='cuda:0')
tensor([0.3055], dtype=torch.float64)
